### ISSUE TITLE
.xcodeproj missing

### ISSUE THREAD

**Issue by praveenkumar56060** [spotlessicode/CoreDataTutorial#1]
Hello, 

I can't see anywhere in your tutorial's .xcodeproj to run the applicaiton.

**Comment by spotlessicode** [comment]
Hi,

I have updated it just now!

;)

SpotlessGirl

**Comment by praveenkumar56060** [comment]
No, i couldn't see it. You sure that you've published it yet?

**Comment by spotlessicode** [comment]
Hi,

Sorry, I did it yesterday with CoreDataTutorial iCloud Sync project. It seems there was an issue at my desktop GitHub App. And now i can’t update this CoreDataTutorial Project. 
Finally I have created a new repo with all files.
You can find here:
https://github.com/spotlessicode/CoreDataTutorialUpdate https://github.com/spotlessicode/CoreDataTutorialUpdate

I hope everything will be ok now!

bests,

SpotlessGirl
